// Intercom API Configuration
// This file is auto-generated from environment variables
// DO NOT EDIT MANUALLY - This file is generated by build-config.js
// Run "npm run build:config" to generate this file from your .env
window.intercomConfig = {
    // Your Intercom Personal Access Token
    // Get it from: https://app.intercom.com/a/apps/_/settings/api
    accessToken: '',
    
    // API Base URL
    apiBaseUrl: 'https://api.intercom.io',
    
    // App ID (optional, for UI links)
    appId: ''
};
