// Intercom API Configuration
// This file is auto-generated from environment variables
// DO NOT EDIT MANUALLY - This file is generated by build-config.js
// NOTE: accessToken is not included here for security - it's only used server-side
window.intercomConfig = {
    // API Base URL
    apiBaseUrl: 'https://api.intercom.io',
    
    // App ID (safe to expose - used for UI links)
    appId: 'aphmhtyj'
};
